source 'https://rubygems.org'
ruby '2.2.2'


gem 'rails', '4.1.8'
gem 'mysql2', group: [:development, :test]
gem 'pg', group: :production
gem 'puma', group: :production
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'

gem 'rails_12factor', group: :production

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem "font-awesome-rails"
gem 'github-pages'

gem 'sdoc', '~> 0.4.0',          group: :doc

gem 'spring',        group: :development

gem 'bcrypt', '~> 3.1.7'

gem 'rspec-rails', '~> 2.0', group: [:development, :test]

gem 'capybara', '~> 2.1.0', group: :test

gem 'shoulda-matchers', group: :test

gem 'factory_girl_rails', '~> 4.0', group: [:development, :test]
gem 'rspec-activemodel-mocks', group: :test

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

